import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
import os

print("Generating physical 3D conformations of Aspirin...")
# 1. Build Aspirin
mol = Chem.MolFromSmiles('CC(=O)Oc1ccccc1C(=O)O')
mol = Chem.AddHs(mol)

# 2. Generate 50 physical conformations
# This simulates the physical folding/wiggling space of the molecule!
AllChem.EmbedMultipleConfs(mol, numConfs=50, randomSeed=42, pruneRmsThresh=0.1)

# 3. Optimize them with MMFF94 to make sure they are physically realistic
for conf in mol.GetConformers():
    AllChem.MMFFOptimizeMolecule(mol, confId=conf.GetId())

# 4. Extract as a multi-model SDF string
sdf_blocks = []
for conf in mol.GetConformers():
    sdf_blocks.append(Chem.MolToMolBlock(mol, confId=conf.GetId()))

# Join blocks with standard SDF delimiter
traj_str = "\n$$$$\n".join(sdf_blocks) + "\n$$$$\n"
# Escape newlines for javascript string literal
traj_str_js = traj_str.replace("\n", "\\n")

# 5. Generate Interactive HTML with py3Dmol JS
print("Packaging into interactive HTML Viewer...")
html = f"""
<html>
<head>
    <title>Molecular Dynamics Demo</title>
    <!-- Load jQuery and 3Dmol.js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
    <style>
        body {{ margin: 0; overflow: hidden; background-color: #111; color: white; font-family: 'Inter', sans-serif; }}
        #container {{ width: 100vw; height: 100vh; position: relative; }}
        #title {{ 
            position: absolute; top: 30px; left: 40px; z-index: 10; 
            background: rgba(0,0,0,0.6); padding: 20px; border-radius: 12px;
            backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.1);
            max-width: 400px;
        }}
        h2 {{ margin: 0 0 10px 0; color: #4ade80; }}
        p {{ margin: 0; line-height: 1.5; color: #cbd5e1; font-size: 14px; }}
    </style>
</head>
<body>
    <div id="title">
        <h2>Aspirin Molecular Dynamics</h2>
        <p>You are looking at 50 physical conformations of Aspirin (21 atoms).</p>
        <p style="margin-top: 10px;">Click and drag to rotate the molecule. Scroll to zoom.</p>
        <p style="margin-top: 10px;">This exact physical wiggling is what your Kaggle pipeline is currently computing for the 1,600-atom Human Prion protein across 1,000,000 frames!</p>
    </div>
    
    <div id="container"></div>
    
    <script>
        $(document).ready(function() {{
            // The massive molecular string generated by RDKit
            var trajectory = `{traj_str_js}`;
            
            // Initialize 3Dmol viewer
            let viewer = $3Dmol.createViewer("container", {{defaultcolors: $3Dmol.rasmolElementColors}});
            
            // Add all 50 frames
            viewer.addModelsAsFrames(trajectory, "sdf");
            
            // Apply beautiful premium styling
            viewer.setStyle({{}}, {{
                stick: {{radius: 0.15, colorscheme: 'Jmol'}}, 
                sphere: {{scale: 0.3, colorscheme: 'Jmol'}}
            }});
            
            viewer.zoomTo();
            
            // Start the physics animation loop (100ms per frame)
            viewer.animate({{loop: "forward", step: 1, interval: 100}});
            viewer.render();
        }});
    </script>
</body>
</html>
"""

output_path = os.path.join(os.getcwd(), "demo.html")
with open(output_path, "w") as f:
    f.write(html)
print(f"\u2714\ufe0f Success! The interactive visualization has been saved to: {output_path}")
print("Double-click demo.html in your folder to open it in your browser!")
